Lint/DuplicateMethods:
  Exclude:
    - 'lib/mailinator/config.rb'

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Max: 33

Metrics/MethodLength:
  Max: 15

Style/BlockDelimiters:
  Exclude:
    - 'spec/lib/mailinator/inbox_private_spec.rb'

Style/DateTime:
  Exclude:
    - 'lib/mailinator/models/email.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/mailinator.rb'
    - 'lib/mailinator/api.rb'
    - 'lib/mailinator/config.rb'
    - 'lib/mailinator/email.rb'
    - 'lib/mailinator/inbox.rb'
    - 'lib/mailinator/model.rb'
    - 'lib/mailinator/models/email.rb'
    - 'lib/mailinator/models/entry.rb'
    - 'lib/mailinator/models/inbox.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 185
